export const ShortName = {
    'The Tarragrue': 'Tarragrue',
    'The Eye of the Jailer': 'The Eye',
    'The Nine': 'The Nine',
    "Remnant of Ner'zhul": "Ner'zhul",
    'Soulrender Dormazain': 'Soulrender',
    'Painsmith Raznal': 'Painsmith',
    'Guardian of the First Ones': 'Guardian',
    'Fatescribe Roh-Kalo': 'Fatescribe',
    "Kel'Thuzad": 'KT',
    'Sylvanas Windrunner': 'Sylvanas',
    'Dausegne, the Fallen Oracle': 'Dausegne',
    "Artificer Xy'mox": "Artificer",
    'Skolex, the Insatiable Ravener': 'Skolex',
    'Halondrus the Reclaimer': 'Halondrus',
    'Lihuvim, Principal Architect': 'Lihuvim',
    'Anduin Wrynn': 'Anduin',
};
